import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { CustomizableMenu } from "@/components/customizable-menu";
import AppNavbar from "@/components/app-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-screen bg-[#F5F5F5]`}
      >
        <SidebarProvider>
          <div className="flex flex-col h-full w-full">
            <AppNavbar />
            <div className="flex h-full">
              <CustomizableMenu />
              <main>{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
