import AppNavbar from "@/components/app-navbar";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased min-h-screen w-screen bg-[#F5F5F5]`}
      >
        <SidebarProvider>
          <div className="flex flex-col h-full w-full">
            <AppNavbar />
            <div className="flex h-full w-full">
              <AppSidebar />
              <main className="h-full flex-1">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
